services:
  keeperdata_api:
    build:
      args:
        TARGETARCH: arm64
    labels:
      com.microsoft.visual-studio.project-name: "KeeperData.Api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5555
      - AWS__ServiceURL=http://kda-localstack-emulator:4566
      - Mongo__DatabaseUri=mongodb://kda_mongodb:27017
      - StorageConfiguration__ComparisonReportsStorage__BucketName=test-comparison-reports-bucket
      - QueueConsumerOptions__IntakeEventQueueOptions__QueueUrl=http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ls_keeper_data_intake_queue
      - QueueConsumerOptions__IntakeEventQueueOptions__DeadLetterQueueUrl=http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ls_keeper_data_intake_queue-deadletter
      - ApiClients__DataBridgeApi__BaseUrl=http://keeperdata_bridge:5560/
      - ApiClients__DataBridgeApi__ServiceName=
      - ApiClients__DataBridgeApi__XApiKey=
      - ApiClients__DataBridgeApi__UseFakeClient=true
      - ServiceBusSenderConfiguration__IntakeEventQueue__QueueUrl=http://sqs.eu-west-2.127.0.0.1:4566/000000000000/ls_keeper_data_intake_queue
      - BatchCompletionNotificationConfiguration__BatchCompletionEventsTopic__TopicName=ls_keeper_data_import_complete
      - BatchCompletionNotificationConfiguration__BatchCompletionEventsTopic__TopicArn=arn:aws:sns:eu-west-2:000000000000:ls_keeper_data_import_complete
      - DataBridgeScanConfiguration__QueryPageSize=5
      - DataBridgeScanConfiguration__DelayBetweenQueriesSeconds=0
      - DataBridgeScanConfiguration__LimitScanTotalBatchSize=10
      - DataBridgeScanConfiguration__DailyScanIncludeChangesWithinTotalHours=24
    ports:
      - "5555"
    volumes:
      # Mac-specific paths for user secrets and HTTPS certificates
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/home/app/.aspnet/https:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      # Mount seed files directly for Rider Fast Mode
      - ./src/KeeperData.Infrastructure/Data/Seed:/app/Data/Seed:ro
